import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { PageIntro } from "@/components/site-shell";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { publicContentOptions } from "@/lib/content.queries";
import { articleImages } from "@/lib/site-data";

export const Route=createFileRoute("/blog")({loader:({context})=>context.queryClient.ensureQueryData(publicContentOptions),head:()=>({meta:[{title:"Journal — Healing Emotions"},{name:"description",content:"Plain-language reflections on emotional wellbeing, relationships, resilience and graphology."},{property:"og:title",content:"The Healing Emotions Journal"},{property:"og:description",content:"Thoughtful ideas for gentler days and healthier relationships."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BlogPage});
function BlogPage(){const{data}=useSuspenseQuery(publicContentOptions);const[q,setQ]=useState("");const[cat,setCat]=useState("all");const filtered=useMemo(()=>data.articles.filter(a=>(cat==="all"||a.categories?.slug===cat)&&(a.title+" "+a.excerpt).toLowerCase().includes(q.toLowerCase())),[data.articles,q,cat]);return <><PageIntro eyebrow="The journal" title="Words for what you might be feeling" description="Grounded reflections—written to be useful, never overwhelming."/><section className="py-16"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="flex flex-col gap-4 border-b border-border pb-8 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the journal" className="h-10 pl-10"/></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={cat==="all"?"default":"outline"} onClick={()=>setCat("all")}>All</Button>{data.categories.map(c=><Button key={c.id} size="sm" variant={cat===c.slug?"default":"outline"} onClick={()=>setCat(c.slug)}>{c.name}</Button>)}</div></div>{filtered.length?<div className="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{filtered.map(a=><Link key={a.id} to="/blog/$slug" params={{slug:a.slug}} className="group"><img src={articleImages[a.slug]} alt="" className="aspect-[4/3] w-full rounded-lg object-cover"/><p className="mt-5 text-xs text-primary">{a.categories?.name} · {a.reading_minutes} min</p><h2 className="mt-2 font-serif text-2xl leading-tight text-earth group-hover:text-primary">{a.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{a.excerpt}</p></Link>)}</div>:<div className="py-20 text-center text-muted-foreground">No journal entries match your search.</div>}</div></section></>}