import { createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowRight } from "lucide-react";
import { PageIntro } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { publicContentOptions } from "@/lib/content.queries";
import { contact, fallbackServices } from "@/lib/site-data";

export const Route = createFileRoute("/services")({ loader: ({ context }) => context.queryClient.ensureQueryData(publicContentOptions), head: () => ({ meta: [{title:"Therapy, Coaching & Wellbeing Services — Healing Emotions"},{name:"description",content:"Explore individual, couple, family and child support, coaching, corporate wellness and graphology."},{property:"og:title",content:"Services — Healing Emotions"},{property:"og:description",content:"Human-centred support for individuals, families and workplaces."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: ServicesPage });
function ServicesPage(){ const {data}=useSuspenseQuery(publicContentOptions); const items=data.services.length?data.services:fallbackServices; return <><PageIntro eyebrow="How we help" title="Support for the whole, complicated person" description="Different seasons call for different kinds of support. We begin with your experience, not a label."/><section className="py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="divide-y divide-border">{items.map((item,i)=><article key={item.title} className="grid gap-6 py-10 md:grid-cols-[120px_1fr_1fr]"><span className="text-sm text-primary">0{i+1}</span><h2 className="font-serif text-3xl text-earth">{item.title}</h2><div><p className="leading-7 text-muted-foreground">{item.summary}</p>{"body" in item&&<p className="mt-3 text-sm leading-6 text-muted-foreground">{item.body}</p>}</div></article>)}</div><div className="mt-14 rounded-lg bg-sage-soft p-8 text-center"><h2 className="font-serif text-3xl text-earth">Unsure what fits?</h2><p className="mt-3 text-muted-foreground">Tell us what is on your mind and we will help you understand the available options.</p><Button asChild className="mt-6 rounded-full"><a href={contact.whatsapp} target="_blank" rel="noreferrer">Start with a message <ArrowRight/></a></Button></div></div></section></> }